import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import NavigationBar from "@/components/global/navigationBar";
import SideBar from "@/components/global/sideBar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationBar/>
        <SideBar/>
        <div className="min-w-full min-h-screen bg-white text-black pt-[81px] pl-[65px]">
        {children}
        </div>
      </body>
    </html>
  );
}
